name: UniverseNicks
version: ${project.version}
main: dev.rajaopak.universenick.Nicks
api-version: 1.13
authors: [Majekdor, rajaopak]
description: ${project.description}
softdepend: [PlaceholderAPI, Vault]
commands:
  nick:
    description: Change your nickname.
    usage: /nick <nickname>
    permission: universenetwork.nick
  nickother:
    description: Change the nickname of another player.
    usage: /nickother <player> <nickname>
    permission: universenetwork.nick.other
  nickreset:
    description: Remove your nickname entirely.
    usage: /nickreset [player]
    permission: universenetwork.nickreset
  nickcolor:
    description: Change the color of your nickname.
    usage: /nickcolor <color>
    permission: universenetwork.nickcolor
  nicksreload:
    description: Reload the plugin.
    usage: /nicksreload
    permission: universenetwork.reload

permissions:
  universenetwork.nick:
    description: Permission to change nicknames.
    default: true
  universenetwork.nick.other:
    description: Permission to change other player's nicknames.
    default: op
  universenetwork.nickreset:
    description: Permission to remove nicknames.
    default: true
  universenetwork.nickreset.other:
    description: Permission to remove other player's nicknames.
    default: op
  universenetwork.nickcolor:
    description: Permission to change color of nickname.
    default: true
  universenetwork.reload:
    description: Permission to reload the plugin.
    default: op