name: UniverseNick
version: ${project.version}
main: dev.rajaopak.universenick.Nicks
api-version: 1.13
authors: [Majekdor, rajaopak]
description: ${project.description}
softdepend: [PlaceholderAPI, Vault]
commands:
  nick:
    description: Change your nickname.
    usage: /nick <nickname>
    permission: hexnicks.nick
  nickother:
    description: Change the nickname of another player.
    usage: /nickother <player> <nickname>
    permission: hexnicks.nick.other
  nonick:
    description: Remove your nickname entirely.
    usage: /nonick [player]
    permission: hexnicks.nonick
  nickcolor:
    description: Change the color of your nickname.
    usage: /nickcolor <color>
    permission: hexnicks.nickcolor
  nicksreload:
    description: Reload the plugin.
    usage: /nicksreload
    permission: hexnicks.reload

permissions:
  hexnicks.nick:
    description: Permission to change nicknames.
    default: true
  hexnicks.nick.other:
    description: Permission to change other player's nicknames.
    default: op
  hexnicks.nonick:
    description: Permission to remove nicknames.
    default: true
  hexnicks.nonick.other:
    description: Permission to remove other player's nicknames.
    default: op
  hexnicks.nickcolor:
    description: Permission to change color of nickname.
    default: true
  hexnicks.reload:
    description: Permission to reload the plugin.
    default: op